name: Hit endpoints

on: 
  schedule:
    - cron: '*/15 09-17 * * *'

jobs:
  refresh-endpoints:
    runs-on: ubuntu-latest
    environment: ScriptsEnv
    steps:
      - uses: actions/checkout@v3

      - name: Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "scripts/requirements.txt"
      
      - name: Run Script
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_APP: ${{ secrets.MONGO_APP }}
          PLAYER_LIST_URL: ${{ secrets.PLAYER_LIST_URL }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: |
          cd scripts
          python3 hit_endpoints.py